from collections import deque
queue=deque()
queue1=deque([1,2,3])
print(queue)
print(queue1)
print()

queue.append(1)
queue.append([2,3,4,5])
print(queue)
print()

queue.appendleft(3)
print(queue)
queue.extend(queue1)
print(queue)
queue.extendleft(queue1)
print(queue)
print()

print(queue.pop())
print(queue.popleft())
queue.rotate(2)
print(queue)
queue.reverse()
print(queue)
queue2=queue.copy()
print(queue.index(2))
n=queue.count(1)
print(n)
queue.clear()
print(queue)